# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d42c76afa267a5fbdab1556f4aaceb8ce282314edc7c7723b63dc7c8a8ec3b163292209eb3ec40fc4dacaf7f8ce4073eb879e8d2945be0a7893d7d0e362047bb

test:
  secret_key_base: 69ccd419d6821cc4351b19d53cb8e880b32886596e5a13cc770c70cd978ff8b317f280abebae484da6be9b4e282d1c58656730413eb5d0dbada7a67022ded577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
